item {id: 1, name: "BondBlue#6"}
item {id: 2, name: "BondBlueSelection"}
item {id: 3, name: "BondBlueSelection25"}
item {id: 4, name: "BondPremiumMix"}
item {id: 5, name: "BondPremiumSilver"}
item {id: 6, name: "BondRedSelection"}
item {id: 7, name: "BondRedSelection25"}
item {id: 8, name: "BondSilverClassic"}
item {id: 9, name: "BondSilverClassic25"}
item {id: 10, name: "ChesterfieldKSBlue"}
item {id: 11, name: "ChesterfieldKSBronze"}
item {id: 12, name: "ChesterfieldKSRed"}
item {id: 13, name: "LMBlueLabel"}
item {id: 14, name: "LMFineCutSilver"}
item {id: 15, name: "LMLoftBlue"}
item {id: 16, name: "LMLoftDoubleSplash"}
item {id: 17, name: "LMLoftMix"}
item {id: 18, name: "LMLoftNightBlue"}
item {id: 19, name: "LMLoftSeaBlue"}
item {id: 20, name: "LMSmartSeriesRed"}
item {id: 21, name: "MarlboroFineTouchLightBlue"}
item {id: 22, name: "MarlboroFlavorMix"}
item {id: 23, name: "MarlboroGold"}
item {id: 24, name: "MarlboroMicro"}
item {id: 25, name: "MarlboroRed"}
item {id: 26, name: "MarlboroSilver"}
item {id: 27, name: "MarlboroTouchBlue"}
item {id: 28, name: "MurattiGreen"}
item {id: 29, name: "MurattiPeach"}
item {id: 30, name: "MurattiPink"}
item {id: 31, name: "MurattyViolet"}
item {id: 32, name: "NextPink"}
item {id: 33, name: "NextViolet"}
item {id: 34, name: "ParliamentAquaBlue"}
item {id: 35, name: "ParliamentAquaSuperSlims"}
item {id: 36, name: "ParliamentCaratBlue"}
item {id: 37, name: "ParliamentCaratPurple"}
item {id: 38, name: "ParliamentNightBlue"}
item {id: 39, name: "ParliamentPearlBlue"}
item {id: 40, name: "ParliamentPlatinum"}
item {id: 41, name: "ParliamentSilverBlue"}
item {id: 42, name: "ParliamentSilverSuperSlims"}
item {id: 43, name: "PhilipMorrisBlue"}
item {id: 44, name: "PhilipMorrisBlue25"}
item {id: 45, name: "PhilipMorrisGold"}
item {id: 46, name: "PhilipMorrisNovelBlue"}
item {id: 47, name: "PhilipMorrisNovelMix"}
item {id: 48, name: "PhilipMorrisNovelRed"}
item {id: 49, name: "PhilipMorrisNovelSilver"}
item {id: 50, name: "PhilipMorrisRed"}
item {id: 51, name: "PhilipMorrisRed25"}
item {id: 52, name: "PhilipMorrisRedKingSize"}